### ISSUE TITLE
EntityID fail

### ISSUE THREAD

**Issue by websitenmaker12** [websitenmaker12/Advanced-Genetics#115]
[09:19:46] [Server thread/ERROR] [FML/Advanced Genetics]: Unable to access any field [entityId] on type net.minecraft.entity.Entity
cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: entityId
        at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:121) ~[forge-1.7.2-10.12.1.1110-universal.jar:?]
        at cpw.mods.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:60) [ObfuscationReflectionHelper.class:?]
        at com.advGenetics.Event.TickEventHandler.onWorldTick(TickEventHandler.java:91) [TickEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_300_TickEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) [ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:629) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326) [lj.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669) [kx.class:?]
Caused by: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: entityId
        at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:94) ~[forge-1.7.2-10.12.1.1110-universal.jar:?]
        at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117) ~[forge-1.7.2-10.12.1.1110-universal.jar:?]
        ... 11 more
Caused by: java.lang.NoSuchFieldException: entityId
        at java.lang.Class.getDeclaredField(Class.java:1948) ~[?:1.7.0_55]
        at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:85) ~[forge-1.7.2-10.12.1.1110-universal.jar:?]
        at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117) ~[forge-1.7.2-10.12.1.1110-universal.jar:?]
        ... 11 more

**Comment by websitenmaker12** [comment]
Fixed in 1.5.5
