### ISSUE TITLE
Crash when placing DNA Analyzer

### ISSUE THREAD

**Issue by 61352151511** [websitenmaker12/Advanced-Genetics#121]
Server decided to go in a start/stop loop after that.
AG Version: 1.5.6
IC2: industrialcraft-2-2.2.500-experimental.jar
Minecraft: 1.7.10
Forge: 10.13.0.1177

[12:42:23] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError
    at ic2.core.energy.Grid.prepareCalculation(Grid.java:208) ~[Grid.class:?]
    at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:309) ~[EnergyNetLocal.class:?]
    at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:56) ~[EnergyNetGlobal.class:?]
    at ic2.core.TickHandler.onWorldTick(TickHandler.java:51) ~[TickHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[12:42:23] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server49/./crash-reports/crash-2014-07-09_12.42.23-server.txt

**Comment by TheOnlyRupert** [comment]
I'm getting the same error.. using the most recent ic2 and ag

**Comment by websitenmaker12** [comment]
Fixed in the next version.
