### ISSUE TITLE
PreInit warning

### ISSUE THREAD

**Issue by websitenmaker12** [websitenmaker12/Advanced-Genetics#129]
Running Advanced Genetics in a 1.7.10 server causes the following scream warnings from FML:

[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: ****************************************
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \* Illegal extra prefix advGen for name advGen:dnaanalyser, invalid registry invocation/invalid name?
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:809)
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:198)
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:187)
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at com.advGenetics.Proxy.CommonProxy.registerBlock(CommonProxy.java:19)
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: \*  at com.advGenetics.AdvGenetics.preLoad(AdvGenetics.java:333)...
[11:05:20] [Server thread/WARN] [advancedgenetics@ModLog]: ****************************************

**Comment by websitenmaker12** [comment]
Yes. I noticed that but when I change this now a lot of people will probably loose their AG machines.
