### ISSUE TITLE
Invalid name

### ISSUE THREAD

**Issue by LemADEC** [websitenmaker12/Advanced-Genetics#146]
FML is complaining about the names used in the mod:

```
[09:59:31] [Client thread/WARN]: ****************************************
[09:59:31] [Client thread/WARN]: * Illegal extra prefix advGen for name advGen:dnaanalyser, invalid registry invocation/invalid name?
[09:59:31] [Client thread/WARN]: *  at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:855)
[09:59:31] [Client thread/WARN]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:223)
[09:59:31] [Client thread/WARN]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:182)
[09:59:31] [Client thread/WARN]: *  at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:171)
[09:59:31] [Client thread/WARN]: *  at com.advGenetics.Proxy.CommonProxy.registerBlock(CommonProxy.java:19)
[09:59:31] [Client thread/WARN]: *  at com.advGenetics.AdvGenetics.preLoad(AdvGenetics.java:333)...
[09:59:31] [Client thread/WARN]: ****************************************
```

and the list goes on for pages...

**Comment by LemADEC** [comment]
advancedgenetics-1.7.10-1.5.7.jar
Forge Mod Loader version 7.10.85.1236 for Minecraft 1.7.10

**Comment by websitenmaker12** [comment]
This problem was already reported but I don't have a solution for it. I'm afraid that when I change the name of the items they will vanish ingame.

**Comment by LemADEC** [comment]
You could add a remapping mod to address that?
