### ISSUE TITLE
Hoppers under machines crash game

### ISSUE THREAD

**Issue by tahornback** [websitenmaker12/Advanced-Genetics#15]
Crash Report

[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] ---- Minecraft Crash Report ----
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] // Oh - I know what I did wrong!
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Time: 12/15/13 1:26 PM
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Description: Ticking tile entity
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] java.lang.ClassCastException: net.minecraft.entity.item.EntityItem cannot be cast to net.minecraft.inventory.IInventory
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96117_b(TileEntityHopper.java:552)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96118_b(TileEntityHopper.java:509)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96116_a(TileEntityHopper.java:307)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_98045_j(TileEntityHopper.java:250)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_70316_g(TileEntityHopper.java:238)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.world.World.func_72939_s(World.java:2271)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:642)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] -- Head --
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Stacktrace:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96117_b(TileEntityHopper.java:552)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96118_b(TileEntityHopper.java:509)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_96116_a(TileEntityHopper.java:307)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_98045_j(TileEntityHopper.java:250)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.tileentity.TileEntityHopper.func_70316_g(TileEntityHopper.java:238)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] -- Tile entity being ticked --
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Details:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Name: Hopper // net.minecraft.tileentity.TileEntityHopper
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Block data value: 0 / 0x0 / 0b0000
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Block location: World: (149,61,287), Chunk: (at 5,3,15 in 9,17; contains blocks 144,0,272 to 159,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Actual block data value: 0 / 0x0 / 0b0000
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Stacktrace:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.world.World.func_72939_s(World.java:2271)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:642)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] -- Affected level --
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Details:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level name: Advanced Genetics
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    All players: 0 total; []
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Chunk stats: ServerChunkCache: 625 Drop: 0
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level seed: 9163036471843010668
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level generator: ID 00 - default, ver 1. Features enabled: true
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level generator options: 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level spawn location: World: (86,64,265), Chunk: (at 6,4,9 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level time: 8861 game time, 3361 day time
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level dimension: 0
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level storage version: 0x04ABD - Anvil
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level weather: Rain time: 152627 (now: false), thunder time: 33634 (now: false)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Stacktrace:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] 
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] -- System Details --
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] Details:
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Minecraft Version: 1.6.4
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Operating System: Windows 8 (x86) version 6.2
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Java Version: 1.7.0_45, Oracle Corporation
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Memory: 25498824 bytes (24 MB) / 192253952 bytes (183 MB) up to 518979584 bytes (494 MB)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    AABB Pool Size: 3117 (174552 bytes; 0 MB) allocated, 3117 (174552 bytes; 0 MB) used
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Suspicious classes: FML and Forge are installed
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 11 mods loaded, 11 mods active
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MMM_metaworlds_patcher{0.972} [Metaworlds_patcher](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    advancedgenetics{v1.9 BETA} [Advanced Genetics](advancedGenetics_vb1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsMod{0.972} [MetaworldsMod](metaworlds_core.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsControlsAlignMod{0.972} [MetaworldsControlsAlignMod](metaworlds_controller.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsControlsCaptainMod{0.972} [MetaworldsControlsCaptainMod](metaworlds_controller.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsBlankCreatorMod{0.972} [MetaworldsBlankCreatorMod](metaworlds_creator.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsContagiousCreatorMod{0.972} [MetaworldsContagiousCreatorMod](metaworlds_creator.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    MetaworldsMiniatureMod{0.972} [MetaworldsMiniatureMod](miniature_mod_V0_972b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Profiler Position: N/A (disabled)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Vec3 Pool Size: 2242 (125552 bytes; 0 MB) allocated, 2242 (125552 bytes; 0 MB) used
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Player Count: 0 / 8; []
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Type: Integrated Server (map_client.txt)
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT]    Is Modded: Definitely; Client brand changed to 'fml,forge'
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [STDOUT] #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Tim\AppData\Roaming.minecraft\crash-reports\crash-2013-12-15_13.26.42-server.txt
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [Minecraft-Server] Stopping server
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [Minecraft-Server] Saving players
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [Minecraft-Server] Saving worlds
[13:26:42 INFO]: Client> 2013-12-15 13:26:42 [INFO] [Minecraft-Server] Saving chunks for level 'Advanced Genetics'/Overworld
[13:26:44 INFO]: Client> AL lib: (EE) alc_cleanup: 1 device not closed
[13:26:44 ERROR]: Game ended with bad state (exit code -1)
[13:26:44 INFO]: Deleting C:\Users\Tim\AppData\Roaming.minecraft\versions\1.6.4-Forge9.11.1.953\1.6.4-Forge9.11.1.953-natives-90395406527595
[13:26:44 INFO]: Ignoring visibility rule and showing launcher due to a game crash

**Comment by websitenmaker12** [comment]
Do you have any other mods installed?

**Comment by tahornback** [comment]
Yes, Metaworlds with Miniature submod.

**Comment by websitenmaker12** [comment]
This is probably a bug in Metaworld or Miniature. Anyway, wait for the next update. Serval bugs are fixed!
