### ISSUE TITLE
Problems upgrading?

### ISSUE THREAD

**Issue by dgbonomo** [websitenmaker12/Advanced-Genetics#154]
Hi, I run a private server that uses a modified FeedTheBeast direwolf20 pack for me and a few friends.  I tried to upgrade from 1.5.7 to 1.5.8 but am running into the following issue:

```
-----cut-----
[14:46:27] [Server thread/INFO] [fml.ModTracker]: This world was saved with mod advancedgenetics version 1.5.7 and it is now at version 1.5.8, things may not work well
[14:46:27] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnasplitter
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnainsulator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:homeostasistube
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaencoder
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:centrifuge
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnatransmutator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:microscope
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:combustiongenerator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:deathenderchest
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:autoscraper
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:combustiongeneratoridle
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaremover
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnacloner
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnacombiner
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:healcrystalblock
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaextractor
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnabreeder
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaanalyser
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaautosplitter
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:helix
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:syringe
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:gene
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:syringebloody
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:helixinsulated
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaextractor
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:advanceddictionary
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnatransmutator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:deathenderchest
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:combustiongeneratoridle
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:invalidCell
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnainsulator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:magnifier
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaencoder
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:cellinstulated
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:stonestick
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:geneticbow
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:combustiongenerator
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:overclocker
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:skinscales
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:healcrystalblock
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:homeostasistubeitem
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:antidotesyringe
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:autoscraper
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnasplitter
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:healCrystal
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:antigene
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnabreeder
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:organicdrop
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:cell
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaautosplitter
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnacloner
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnacombiner
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaremover
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:syringebloodymob
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:dnaanalyser
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:homeostasistube
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:centrifuge
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:basicdictionary
[14:46:27] [ic2-poolthread-1/INFO] [IC2]: UU graph built with 8137 nodes after 10340 ms.
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:scraper
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:microscope
[14:46:27] [Server thread/INFO] [FML]: Found a missing id from the world advancedgenetics:advGen:autooutputupgrade
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnasplitter: 229 (init) -> 1924 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnainsulator: 242 (init) -> 1915 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:homeostasistube: 244 (init) -> 1928 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnaencoder: 228 (init) -> 1922 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:centrifuge: 231 (init) -> 1911 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnatransmutator: 234 (init) -> 1912 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:microscope: 239 (init) -> 1920 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:combustiongenerator: 236 (init) -> 1925 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:deathenderchest: 238 (init) -> 1926 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:autoscraper: 241 (init) -> 1927 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:combustiongeneratoridle: 237 (init) -> 1921 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnaremover: 233 (init) -> 1913 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnacloner: 243 (init) -> 1923 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnacombiner: 232 (init) -> 1917 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:healcrystalblock: 240 (init) -> 1929 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnaextractor: 227 (init) -> 1919 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnabreeder: 230 (init) -> 1916 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnaanalyser: 226 (init) -> 1914 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed block id mismatch advancedgenetics:dnaautosplitter: 235 (init) -> 1918 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed item id mismatch advancedgenetics:helix: 4298 (init) -> 6140 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed item id mismatch advancedgenetics:syringe: 4300 (init) -> 6143 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed item id mismatch advancedgenetics:gene: 4299 (init) -> 6126 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed item id mismatch advancedgenetics:syringebloody: 4301 (init) -> 6129 (map).
[14:46:27] [Server thread/INFO] [FML]: Fixed item id mismatch advancedgenetics:helixinsulated: 4309 (init) -> 6125 (map).
java.lang.ClassCastException: com.advGenetics.Blocks.BlockDNAExtractor cannot be cast to net.minecraft.item.Item
        at cpw.mods.fml.common.registry.GameData.processIdRematches(GameData.java:619)
        at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:929)
        at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:537)
        at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:275)
        at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403)
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:201)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[14:46:27] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

If I do try to proceed past that point, the world is indeed corrupted and none of the mod blocks are what they were, with the client crashing shortly thereafter.  I've not run into a similar issue before - please advice on what else to do/post?

**Comment by tim-oster** [comment]
Redownload the version and try it again (I made a hidden update)
