### ISSUE TITLE
Block type: ID #722 (tile.dnaTransmutator creating croupt chunks

### ISSUE THREAD

**Issue by sparkey90** [websitenmaker12/Advanced-Genetics#163]
B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] ---- Minecraft Crash Report ----
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] // Oops.
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Time: 6/16/15 11:14 PM
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Description: Ticking tile entity
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] java.lang.NullPointerException
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at com.advGenetics.TileEntity.TileEntityDNATransmutator.func_70316_g(TileEntityDNATransmutator.java:209)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.world.World.func_72939_s(World.java:2209)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1921)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.main.Main.main(SourceFile:101)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at java.lang.reflect.Method.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] -- Head --
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Stacktrace:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at com.advGenetics.TileEntity.TileEntityDNATransmutator.func_70316_g(TileEntityDNATransmutator.java:209)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] -- Tile entity being ticked --
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Details:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Name: tileentitydnatransmutator // com.advGenetics.TileEntity.TileEntityDNATransmutator
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Block type: ID #722 (tile.dnaTransmutator // com.advGenetics.Blocks.BlockDNATransmutator)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Block data value: 4 / 0x4 / 0b0100
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Block location: World: (-578,172,2807), Chunk: (at 14,10,7 in -37,175; contains blocks -592,0,2800 to -577,255,2815), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,0,2560 to -513,255,3071)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Actual block type: ID #722 (tile.dnaTransmutator // com.advGenetics.Blocks.BlockDNATransmutator)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Actual block data value: 4 / 0x4 / 0b0100
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Stacktrace:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.world.World.func_72939_s(World.java:2209)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] -- Affected level --
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Details:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level name: MpServer
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    All players: 1 total; [GCCorePlayerSP['sparkey90'/85797, l='MpServer', x=-420.78, y=147.66, z=2939.11]]
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Chunk stats: MultiplayerChunkCache: 441
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level seed: 0
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level generator options: 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level spawn location: World: (-679,63,2942), Chunk: (at 9,3,14 in -43,183; contains blocks -688,0,2928 to -673,255,2943), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,0,2560 to -513,255,3071)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level time: 526579966 game time, 350553212 day time
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level dimension: 0
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level storage version: 0x00000 - Unknown?
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Forced entities: 31 total; [EntityItem['item.item.Organs'/85884, l='MpServer', x=-407.31, y=30.13, z=2968.47], EntityItem['item.item.string'/85885, l='MpServer', x=-408.47, y=30.13, z=2967.03], EntityJungleSpider['Jungle Spider'/85886, l='MpServer', x=-406.91, y=36.00, z=2967.28], EntityCow['Cow'/85887, l='MpServer', x=-388.94, y=65.00, z=2897.91], EntityZombie['Zombie'/85880, l='MpServer', x=-399.50, y=24.00, z=2916.50], EntityZombie['Zombie'/85881, l='MpServer', x=-386.62, y=62.84, z=2911.52], EntityCow['Cow'/85882, l='MpServer', x=-390.10, y=64.59, z=2918.40], EntityZombie['Zombie'/85942, l='MpServer', x=-408.50, y=27.00, z=2962.50], EntityZombie['Zombie'/85883, l='MpServer', x=-415.16, y=24.00, z=2972.53], EntityJungleSpider['Jungle Spider'/85876, l='MpServer', x=-430.47, y=31.00, z=2968.88], EntityZombie['Zombie'/85877, l='MpServer', x=-419.50, y=27.00, z=2974.94], GCCorePlayerSP['sparkey90'/85797, l='MpServer', x=-420.78, y=147.66, z=2939.11], EntityJungleSpider['Jungle Spider'/85878, l='MpServer', x=-435.63, y=27.25, z=2974.48], EntitySquid['Squid'/85879, l='MpServer', x=-440.14, y=58.93, z=2901.93], EntitySquid['Squid'/85872, l='MpServer', x=-413.28, y=60.45, z=2926.38], EntityCreeper['Creeper'/85873, l='MpServer', x=-413.00, y=20.00, z=2958.50], EntityCow['Cow'/85874, l='MpServer', x=-384.94, y=63.00, z=2930.91], EntityJungleSpider['Jungle Spider'/85875, l='MpServer', x=-420.66, y=24.00, z=2964.50], EntityZombie['Zombie'/85871, l='MpServer', x=-401.97, y=24.00, z=2915.97], EntitySquid['Squid'/85870, l='MpServer', x=-430.84, y=61.93, z=2932.42], EntitySquid['Squid'/85798, l='MpServer', x=-430.13, y=61.72, z=2931.39], EntityHat['unknown'/230, l='MpServer', x=-420.78, y=146.76, z=2939.11], EntityBat['Bat'/85890, l='MpServer', x=-391.35, y=37.70, z=2955.95], EntityCreeper['Creeper'/85891, l='MpServer', x=-466.09, y=62.35, z=2931.69], EntityZombie['Zombie'/85888, l='MpServer', x=-394.50, y=26.20, z=2971.50], EntityZombie['Zombie'/85889, l='MpServer', x=-393.69, y=36.00, z=2960.41], EntityZombie['Zombie'/85894, l='MpServer', x=-407.75, y=35.00, z=2985.84], EntityJungleSpider['Jungle Spider'/85895, l='MpServer', x=-407.22, y=35.00, z=2980.80], EntitySkeleton['Skeleton'/85892, l='MpServer', x=-440.42, y=27.59, z=2975.46], EntityJungleSpider['Jungle Spider'/85896, l='MpServer', x=-408.50, y=35.00, z=2985.50], EntityCow['Cow'/85897, l='MpServer', x=-396.38, y=69.00, z=2893.56]]
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Retry entities: 0 total; []
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Server brand: mcpc,craftbukkit,fml,forge
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Server type: Non-integrated multiplayer server
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Stacktrace:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.client.main.Main.main(SourceFile:101)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at java.lang.reflect.Method.invoke(Unknown Source)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] 
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] -- System Details --
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT] Details:
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Minecraft Version: 1.6.4
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Operating System: Windows 8 (amd64) version 6.2
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Java Version: 1.7.0_79, Oracle Corporation
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Memory: 388162672 bytes (370 MB) / 1156055040 bytes (1102 MB) up to 2863661056 bytes (2731 MB)
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    AABB Pool Size: 18548 (1038688 bytes; 0 MB) allocated, 385 (21560 bytes; 0 MB) used
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    Suspicious classes: FML and Forge are installed
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 118 mods loaded, 118 mods active
[B#301]  2015-06-16 23:14:23 [INFO] [STDOUT]    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available

**Comment by tim-oster** [comment]
Which items did you put into the Transmutator?

**Comment by sparkey90** [comment]
i think its wooly but i culd be rong

**Comment by sparkey90** [comment]
just organic drops

**Comment by MJRLegends** [comment]
@websitenmaker12 did you ever fix this as im getting the same crash??
