### ISSUE TITLE
syringe in chest crash

### ISSUE THREAD

**Issue by omega420** [websitenmaker12/Advanced-Genetics#24]
when we placed 5 filled syringes with abilities teleport, infinity, destruction fireballs, save inventory, fly, no fall, ender health, waterbreathing, and lava swimming, into a regular chest, when you go to access the chest the game crashes with the message "Internal exception: java.io.ioexception:Bad packet id 2. this was on a Horizons modpack server. Both me and my brother experienced it but others can be on the server as long as they don't touch the chest. Both of us crash immediately on returning to the sever but the single player is fine.

**Comment by omega420** [comment]
update. it only crashes when you like look at that area/chunk maybe. i had a slight moment to move away from the area to not get the crash, very strange.

**Comment by websitenmaker12** [comment]
Strange. But I am glad that this isn't an issue of my mod. ;)

**Comment by CWW256** [comment]
I have experienced this exact same problem using advancedGenetics_v1.2.1 included in FTB Monster 1.0.7

**Comment by CWW256** [comment]
Generated on server ocationally when crash occours
2014-01-27 20:34:09 [INFO] [STDERR] java.net.SocketException: Software caused connection abort: recv failed
2014-01-27 20:34:09 [INFO] [STDERR]     at java.net.SocketInputStream.socketRead0(Native Method)
2014-01-27 20:34:09 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at java.io.FilterInputStream.read(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at java.io.DataInputStream.readUnsignedByte(Unknown Source)
2014-01-27 20:34:09 [INFO] [STDERR]     at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:145)
2014-01-27 20:34:09 [INFO] [STDERR]     at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:325)
2014-01-27 20:34:09 [INFO] [STDERR]     at net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:549)
2014-01-27 20:34:09 [INFO] [STDERR]     at net.minecraft.network.TcpReaderThread.run(SourceFile:94)
2014-01-27 20:34:09 [INFO] [Minecraft-Server] player lost connection: disconnect.genericReason

Generated on Client when crash occours
2014-01-27 20:33:56 [INFO] [STDERR] java.io.IOException: Bad packet id 2
2014-01-27 20:33:56 [INFO] [STDERR] at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:149)
2014-01-27 20:33:56 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:325)
2014-01-27 20:33:56 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:549)
2014-01-27 20:33:56 [INFO] [STDERR] at net.minecraft.network.TcpReaderThread.run(SourceFile:94)
