### ISSUE TITLE
Game crashes when using the scraper on skeletons

### ISSUE THREAD

**Issue by Lochnair** [websitenmaker12/Advanced-Genetics#4]
Using the scraper on skeletons crashes the game because skeletons doesn't have genes.

``` java
java.lang.IllegalArgumentException: Empty string not allowed
    at net.minecraft.nbt.NBTTagString.<init>(SourceFile:15)
    at net.minecraft.nbt.NBTTagCompound.func_74778_a(SourceFile:81)
    at com.advGenetics.Items.ItemScraper.func_111207_a(ItemScraper.java:28)
    at net.minecraft.item.ItemStack.func_111282_a(ItemStack.java:421)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1257)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP. ava:467)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1368)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1867)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:909)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:837)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
```

**Comment by websitenmaker12** [comment]
Thank you for this issue (thanks?!?!) ;)
It will be fixed in the next update.

**Comment by Lochnair** [comment]
Thanks for notifying maybe? ;)
