### ISSUE TITLE
Placed microscope, render problem crashed server?

### ISSUE THREAD

**Issue by pisces7386** [websitenmaker12/Advanced-Genetics#45]
So we placed a microsope in our server and it crashed, we cannot get back in to remove it. We can't figure out what has happened (other than that tile render bit in the first line) or how to fix it. Here is a crash log-

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/28/14 11:17 AM
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
    at com.advGenetics.Blocks.BlockMicroscope.func_71857_b(BlockMicroscope.java:53)
    at net.minecraft.pathfinding.PathFinder.func_82565_a(SourceFile:199)
    at net.minecraft.pathfinding.PathFinder.func_75855_a(SourceFile:180)
    at net.minecraft.pathfinding.PathFinder.func_75858_a(SourceFile:132)
    at net.minecraft.pathfinding.PathFinder.func_75860_b(SourceFile:117)
    at net.minecraft.pathfinding.PathFinder.func_75861_a(SourceFile:88)
    at net.minecraft.pathfinding.PathFinder.func_75857_a(SourceFile:59)
    at net.minecraft.pathfinding.PathFinder.func_75859_a(SourceFile:35)
    at net.minecraft.world.World.func_72844_a(World.java:3833)
    at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:78)
    at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:82)
    at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:41)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:91)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:613)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1993)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:441)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:24)
    at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:192)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1826)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:257)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:29)
    at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:283)
    at net.minecraft.world.World.func_72866_a(World.java:2350)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:719)
    at net.minecraft.world.World.func_72870_g(World.java:2311)
    at net.minecraft.world.World.func_72939_s(World.java:2157)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:... I can add this in if y'all want to see it. 

So we updated, and we are now it all works again.

**Comment by websitenmaker12** [comment]
When you update to version 1.3 this will be fixed.
