### ISSUE TITLE
[Crash-Report] TileEntityAutoScraper/TileEntityDNAAnalyser

### ISSUE THREAD

**Issue by Sir-Will** [websitenmaker12/Advanced-Genetics#61]
Minecraft: 1.6.4 AG: 1.4.1

```
java.lang.AbstractMethodError: com.advGenetics.TileEntity.TileEntityAutoScraper.func_94041_b(ILnet/minecraft/item/ItemStack;)Z
    at com.advGenetics.Lib.AutoOutputHandler.handleAutoOutput(AutoOutputHandler.java:30)
    at com.advGenetics.TileEntity.TileEntityDNAAnalyser.func_70316_g(TileEntityDNAAnalyser.java:198)
    at net.minecraft.world.World.func_72939_s(World.java:2782)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.advGenetics.Lib.AutoOutputHandler.handleAutoOutput(AutoOutputHandler.java:30)
    at com.advGenetics.TileEntity.TileEntityDNAAnalyser.func_70316_g(TileEntityDNAAnalyser.java:198)

-- Tile entity being ticked --
Details:
    Name: tileentitydnaanalyser // com.advGenetics.TileEntity.TileEntityDNAAnalyser
    Block type: ID #1000 (tile.dnaAnalyser // com.advGenetics.Blocks.BlockDNAAnalyser)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (-2134,106,-2211), Chunk: (at 10,6,13 in -134,-139; contains blocks -2144,0,-2224 to -2129,255,-2209), Region: (-5,-5; contains chunks -160,-160 to -129,-129, blocks -2560,0,-2560 to -2049,255,-2049)
    Actual block type: ID #1000 (tile.dnaAnalyser // com.advGenetics.Blocks.BlockDNAAnalyser)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2782)
```

**Comment by websitenmaker12** [comment]
What did you do before this error occured?

**Comment by Sir-Will** [comment]
Upgraded the DNAAnalyser with a auto output upgrade. (DNAAnalyser had items in it and a chest was next to the machine)

**Comment by websitenmaker12** [comment]
Ok. I will check this out.
