### ISSUE TITLE
Crash while scraping zombie pigman

### ISSUE THREAD

**Issue by ghost** [websitenmaker12/Advanced-Genetics#63]
When I scrape zombies and zombie pigmen, the game crashes, giving me this log, but it doesn't happen with creepers, squids, or bats. haven't tried others.
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 3/15/14 3:13 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Empty string not allowed
    at net.minecraft.nbt.NBTTagString.<init>(SourceFile:15)
    at net.minecraft.nbt.NBTTagCompound.func_74778_a(SourceFile:81)
    at com.advGenetics.Items.ItemScraper.func_111207_a(ItemScraper.java:31)
    at net.minecraft.item.ItemStack.func_111282_a(ItemStack.java:421)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1257)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:467)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1369)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1868)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by websitenmaker12** [comment]
Should be fixed.

**Comment by ghost** [comment]
Fixed... as in when? Im using 1.4.1 for 1.6.4 atm

**Comment by websitenmaker12** [comment]
In one of the future updates.

**Comment by ghost** [comment]
future as in not yet released? If so, will this update be availabe for 1.6?
