### ISSUE TITLE
ArrayIndexOutOfBoundsException enderio & advGenetics

### ISSUE THREAD

**Issue by Slind14** [websitenmaker12/Advanced-Genetics#65]
`the ender IO item conduit is trying to pull from the back of the machine`

is this related to ender IO, too. Like the ticket before to buildcraft ?

`java.lang.ArrayIndexOutOfBoundsException: 2
    at com.advGenetics.TileEntity.TileEntityDNAInsulator.func_70301_a(TileEntityDNAInsulator.java:40)
    at crazypants.enderio.conduit.item.ItemConduitNetwork$NetworkedInventory.transferItems(ItemConduitNetwork.java:340)
    at crazypants.enderio.conduit.item.ItemConduitNetwork$NetworkedInventory.onTick(ItemConduitNetwork.java:286)
    at crazypants.enderio.conduit.item.ItemConduitNetwork.doTick(ItemConduitNetwork.java:201)
    at crazypants.enderio.conduit.item.ItemConduitNetwork.access$500(ItemConduitNetwork.java:30)
    at crazypants.enderio.conduit.item.ItemConduitNetwork$InnerTickHandler.tickEnd(ItemConduitNetwork.java:557)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:40)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)`

**Comment by Slind14** [comment]
is the issue solved.

**Comment by websitenmaker12** [comment]
It should be solved in the next version I hope.
