### ISSUE TITLE
ItemHealCrystal

### ISSUE THREAD

**Issue by Jenral** [websitenmaker12/Advanced-Genetics#68]
I get this in my log when I open my inventory

2014-03-22 09:19:18 [INFO] [STDERR] NEI: Omitting #31308:0 ItemHealCrystal 
2014-03-22 09:19:18 [INFO] [STDERR] java.lang.ArrayIndexOutOfBoundsException: 31308 
2014-03-22 09:19:18 [INFO] [STDERR] at net.minecraft.item.ItemBlock.func_77617_a(ItemBlock.java:52) 
2014-03-22 09:19:18 [INFO] [STDERR] at net.minecraft.item.Item.func_77650_f(Item.java:310) 
2014-03-22 09:19:18 [INFO] [STDERR] at codechicken.nei.ItemList$ThreadLoadItems.run(ItemList.java:366)

**Comment by Jenral** [comment]
Forgot to mention using version AdvGenetics v1.4.1 for Minecraft v1.6.4

**Comment by websitenmaker12** [comment]
Yes, I know. This isn't a bug and I hope I can fix this in one of the next versions.
