### ISSUE TITLE
Version 1.4.2 for 1.6.X won't load

### ISSUE THREAD

**Issue by RyelleZylar** [websitenmaker12/Advanced-Genetics#86]
2014-04-21 08:06:44 [SEVERE] [ForgeModLoader] Unable to read the jar file advancedgenetics-1.4.2-1.6.jar - ignoring
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(Unknown Source)
    at java.util.zip.ZipFile.<init>(Unknown Source)
    at java.util.jar.JarFile.<init>(Unknown Source)
    at java.util.jar.JarFile.<init>(Unknown Source)
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:244)
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

2014-04-21 08:06:44 [INFO] [STDERR] Failed to load dependancies.info from advancedgenetics-1.4.2-1.6.jar as JSON
2014-04-21 08:06:44 [INFO] [STDERR] java.util.zip.ZipException: error in opening zip file
2014-04-21 08:06:44 [INFO] [STDERR]     at java.util.zip.ZipFile.open(Native Method)
2014-04-21 08:06:44 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:546)
2014-04-21 08:06:44 [INFO] [STDERR]     at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:538)
2014-04-21 08:06:44 [INFO] [STDERR]     at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:475)
2014-04-21 08:06:44 [INFO] [STDERR]     at codechicken.core.launch.DepLoader.load(DepLoader.java:634)
2014-04-21 08:06:44 [INFO] [STDERR]     at biomesoplenty.asm.BOPFMLLoadingPlugin.<init>(BOPFMLLoadingPlugin.java:20)
2014-04-21 08:06:44 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2014-04-21 08:06:44 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at java.lang.reflect.Constructor.newInstance(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at java.lang.Class.newInstance(Unknown Source)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:427)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
2014-04-21 08:06:44 [INFO] [STDERR]     at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
2014-04-21 08:06:44 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
2014-04-21 08:06:44 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

2014-04-21 08:06:59 [WARNING] [ForgeModLoader] Zip file advancedgenetics-1.4.2-1.6.jar failed to read properly, it will be ignored
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(Unknown Source)
    at java.util.zip.ZipFile.<init>(Unknown Source)
    at java.util.jar.JarFile.<init>(Unknown Source)
    at java.util.jar.JarFile.<init>(Unknown Source)
    at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:41)
    at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42)
    at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71)
    at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:137)
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:353)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:484)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by websitenmaker12** [comment]
Should be fixed.
